import pandas as pd
crashes = pd.read_csv('./CAR-CRASHES-2007.csv', parse_dates=['DT_ACCDN'])
interesting_columns = ['DT_ACCDN',
 'HR_ACCDN',
# 'CD_ETAT_VICTM',
# 'CD_MUNCP',
# 'CIVIC_NUMBER',
# 'RUE_ACCN_TYPE',
 'RUE_ACCDN',
# 'RUE_ACCDN_DIR',
# 'PRES_DE_TYPE',
 'ACCDN_PRES_DE',
# 'ACCDN_PRES_DIR',
 'Address concatenation',
# 'Geocoding address',
# 'LATITUDE',
# 'LONGITUDE',
 'NB_MORT_C',
 'NB_BLESE_GRAVE_C',
 'NB_BLESE_LEGER_C']
crashes[interesting_columns].rename(columns={'DT_ACCDN': 'Date',
 'HR_ACCDN': 'Time',
 'CD_ETAT_VICTM': 'Victim count',
# 'CD_MUNCP',
# 'CIVIC_NUMBER',
# 'RUE_ACCN_TYPE',
 'RUE_ACCDN': 'Street',
# 'RUE_ACCDN_DIR',
# 'PRES_DE_TYPE',
 'ACCDN_PRES_DE': 'Cross Street',
# 'ACCDN_PRES_DIR',
 'Address concatenation': 'Address',
# 'Geocoding address',
# 'LATITUDE',
# 'LONGITUDE',
 'NB_MORT_C': 'Deaths',
 'NB_BLESE_GRAVE_C': 'Serious Injuries',
 'NB_BLESE_LEGER_C': 'Injuries'}).to_csv('car_crashes_2007.csv', index=False)
